"""empty message

Revision ID: 82dead95c34f
Revises: 56f175dbbae6
Create Date: 2026-05-27 12:01:19.243651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82dead95c34f'
down_revision: Union[str, None] = '56f175dbbae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('architectures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('software_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('project_platforms')
    op.drop_table('project_languages')
    op.add_column('projects', sa.Column('language_id', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('platform_id', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('architecture_id', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('software_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'software_types', ['software_type_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'architectures', ['architecture_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'platforms', ['platform_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'languages', ['language_id'], ['id'])
    op.drop_column('projects', 'architecture_type')
    op.drop_column('projects', 'software_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('software_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('architecture_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'software_type_id')
    op.drop_column('projects', 'architecture_id')
    op.drop_column('projects', 'platform_id')
    op.drop_column('projects', 'language_id')
    op.create_table('project_languages',
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('language_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], name='project_languages_language_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='project_languages_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'language_id', name='project_languages_pkey')
    )
    op.create_table('project_platforms',
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('platform_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], name='project_platforms_platform_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='project_platforms_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'platform_id', name='project_platforms_pkey')
    )
    op.drop_table('software_types')
    op.drop_table('architectures')
    # ### end Alembic commands ###
