"""empty message

Revision ID: bfd8c1bda5c8
Revises: f1c2637a22ff
Create Date: 2026-05-24 22:42:01.223042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfd8c1bda5c8'
down_revision: Union[str, None] = 'f1c2637a22ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('project_languages',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'language_id')
    )
    op.create_table('project_platforms',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'platform_id')
    )
    op.add_column('projects', sa.Column('software_type', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('architecture_type', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('target_users_count', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('projects', sa.Column('deadline', sa.Date(), nullable=True))
    op.drop_column('users', 'balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('balance', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('projects', 'deadline')
    op.drop_column('projects', 'links')
    op.drop_column('projects', 'target_users_count')
    op.drop_column('projects', 'architecture_type')
    op.drop_column('projects', 'software_type')
    op.drop_table('project_platforms')
    op.drop_table('project_languages')
    op.drop_table('platforms')
    op.drop_table('languages')
    # ### end Alembic commands ###
