"""empty message

Revision ID: f1c2637a22ff
Revises: e8d4fea44a2f
Create Date: 2026-05-24 20:32:21.103842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1c2637a22ff'
down_revision: Union[str, None] = 'e8d4fea44a2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_project', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_user_sender', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_user_recipient', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_project'], ['projects.id'], name='transactions_id_project_fkey'),
    sa.ForeignKeyConstraint(['id_user_recipient'], ['users.id'], name='transactions_id_user_recipient_fkey'),
    sa.ForeignKeyConstraint(['id_user_sender'], ['users.id'], name='transactions_id_user_sender_fkey'),
    sa.PrimaryKeyConstraint('id', name='transactions_pkey')
    )
    # ### end Alembic commands ###
